import { Inter } from "next/font/google";
import "../globals.css";

const font = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={font.className}>
      <body>
        <div className="min-h-screen bg-zinc-900 text-zinc-400">{children}</div>
      </body>
    </html>
  );
}
